version: '3.9'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: always
    privileged: true
    environment:
      DASHDOT_SHOW_DASH_VERSION: icon_hover
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_USE_IMPERIAL: false
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_ACCEPT_OOKLA_EULA: true
      DASHDOT_WIDGET_LIST: os,cpu,storage,ram,network
      DASHDOT_SHOW_HOST: ${DASHDOT_SHOW_HOST}
      DASHDOT_CUSTOM_HOST: ${DASHDOT_CUSTOM_HOST}
      DASHDOT_PAGE_TITLE: ${DASHDOT_PAGE_TITLE}
    expose:
      - 3001
    volumes:
      - /:/mnt/host:ro
    networks:
      - nginx
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU_APP:-0.5}
          memory: ${LIMIT_RAM_APP:-128M}
        reservations:
          cpus: '0.1'
          memory: 16M
networks:
  default:
  nginx:
    external: true
